apps/donacion/urls.py
from django.urls import path

from . import views

app_name = 'donacion'
urlpatterns = [

	path('registrar_desde_producto/<int:producto_id>', views.RegistrarDesdeProducto, name="registrar_desde_producto"),
	path('registrar', views.Registrar, name="registrar"),
    path('modificar/<int:donacion_id>', views.Modificar, name='modificar'),
	path('listar', views.Listar, name="listar"),
	path('aceptar/<int:donacion_id>', views.Aceptar, name='aceptar'),
	path('rechazar/<int:donacion_id>', views.Rechazar, name='rechazar'),
	path('cancelar/<int:donacion_id>', views.Cancelar, name='cancelar'),
    path('perfil/<int:donacion_id>', views.Perfil, name='perfil'),
]

truek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('donacion/', include('apps.donacion.urls', namespace="donacion")),
    path('intercambio/', include('apps.intercambio.urls', namespace="intercambio")),
    path('usuario/', include('apps.usuario.urls', namespace="usuario")),
    path('producto/', include('apps.producto.urls', namespace="producto")),
    path('page/', include('apps.page.urls', namespace="page")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/donacion/models.py
from django.db import models
from django.utils import timezone

from datetime import date, datetime

from apps.usuario.models import Usuario
from apps.producto.models import Producto

class Donacion(models.Model):

	ESTADOS = (
		('Iniciada','Iniciada'),
		('Recibida','Recibida'),
		('Rechazada','Rechazada'),
	)

	donador = models.ForeignKey(Usuario, related_name="donaciones_realizadas", on_delete=models.CASCADE)
	objecto_servicio = models.ForeignKey(Producto, on_delete = models.CASCADE)
	receptor = models.ForeignKey(Usuario, related_name="donaciones_recibidas", on_delete=models.CASCADE)
	estado = models.CharField(max_length=70, choices=ESTADOS)
	fecha_donacion = models.DateTimeField(verbose_name="Fecha de donación", default=timezone.now)
	fecha_aceptacion = models.DateField(verbose_name="Fecha de aceptación", blank=True, null=True)

apps/donacion/forms.py
from django import forms

from .models import Donacion, Usuario, Producto

import datetime

class RegistrarDonacionForm(forms.ModelForm):
	def __init__(self, donador, *args, **kwargs):
		super(RegistrarDonacionForm, self).__init__(*args, **kwargs)
		self.fields["objecto_servicio"].queryset = Producto.objects.filter(dueno=donador).exclude(estado='Donado').exclude(estado='Intercambiado').exclude(estado='En proceso')
		self.fields["receptor"].queryset = Usuario.objects.exclude(id=donador.id)

	def clean(self):
		cleaned_data = super().clean()
		donador = cleaned_data.get("donador")
		receptor = cleaned_data.get("receptor")

		if donador == receptor:
			mensaje = "El receptor no puede ser el mismo donador"
			self.add_error('donador', mensaje)
			self.add_error('receptor', mensaje)
			
	class Meta:
		model = Donacion
		fields = ('objecto_servicio', 'receptor',)

class RegistrarDonacionDesdeProductoForm(forms.ModelForm):
	def __init__(self, donador, producto, *args, **kwargs):
		super(RegistrarDonacionDesdeProductoForm, self).__init__(*args, **kwargs)
		self.fields["objecto_servicio"].queryset = Producto.objects.filter(id=producto.id)
		self.fields["receptor"].queryset = Usuario.objects.exclude(id=donador.id)
		self.initial["objecto_servicio"] = producto

	def clean(self):
		cleaned_data = super().clean()
		donador = cleaned_data.get("donador")
		receptor = cleaned_data.get("receptor")

		if donador == receptor:
			mensaje = "El receptor no puede ser el mismo donador"
			self.add_error('donador', mensaje)
			self.add_error('receptor', mensaje)

	class Meta:
		model = Donacion
		fields = ('objecto_servicio', 'receptor',)

class ModificarDonacionForm(forms.ModelForm):

	def clean(self):
		cleaned_data = super().clean()
		donador = cleaned_data.get("donador")
		receptor = cleaned_data.get("receptor")

		if donador == receptor:
			mensaje = "El receptor no puede ser el mismo donador"
			self.add_error('donador', mensaje)
			self.add_error('receptor', mensaje)

	class Meta:
		model = Donacion
		fields = ('objecto_servicio', 'receptor',)

apps/donacion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from datetime import date, datetime

from .forms import RegistrarDonacionForm, ModificarDonacionForm,RegistrarDonacionDesdeProductoForm
from .models import Donacion, Producto

@login_required
def Registrar(request):
	
	if request.method == 'POST':
		form = RegistrarDonacionForm(request.user, request.POST)	
		if form.is_valid():
			usuario_actual = Donacion(donador = request.user)
			donacion = form.save(commit=False)
			donacion.donador = request.user
			donacion.estado = 'Iniciada'
			donacion.save()
			producto = donacion.objecto_servicio
			producto.estado = 'En proceso'
			producto.save()
			return redirect('donacion:listar')
	else:
		form = RegistrarDonacionForm(request.user)
	return render(request, 'registrar_donacion.html', {'form': form})

@login_required
def RegistrarDesdeProducto(request, producto_id):
	producto = Producto.objects.get(id=producto_id)
	if request.method == 'POST':
		form = RegistrarDonacionDesdeProductoForm(request.user, producto, data=request.POST)	
		if form.is_valid():
			usuario_actual = Donacion(donador = request.user)
			donacion = form.save(commit=False)
			donacion.donador = request.user
			donacion.estado = 'Iniciada'
			donacion.save()
			producto = donacion.objecto_servicio
			producto.estado = 'En proceso'
			producto.save()
			return redirect('donacion:listar')
	else:
		form = RegistrarDonacionDesdeProductoForm(request.user, producto)
	return render(request, 'registrar_donacion.html', {'form': form})

@login_required
def Modificar(request, donacion_id):
	donacion = Donacion.objects.get(id=donacion_id)
	form = ModificarDonacionForm(instance=donacion)
	if request.method == "POST":
		form = ModificarDonacionForm(request.POST, instance=donacion)
		if form.is_valid():
			donacion = form.save(commit=False)
			donacion.save()
			return redirect('donacion:listar')
	return render(request, 'modificar_donacion.html',{'form': form})

@login_required
def Listar(request):
	from django.db.models import FilteredRelation, Q
	donaciones = Donacion.objects.filter(Q(donador=request.user)|Q(receptor=request.user))
	return render(request, "listar_donaciones.html", {'donaciones':donaciones})

@login_required
def Aceptar(request, donacion_id):
	donacion = Donacion.objects.get(id=donacion_id)

	donacion.estado = 'Recibida'
	donacion.fecha_aceptacion = date.today()
	donacion.save()

	producto = donacion.objecto_servicio
	producto.estado = 'Donado'
	producto.dueno = request.user
	producto.save()
	return redirect('donacion:listar')

@login_required
def Rechazar(request, donacion_id):
	donacion = Donacion.objects.get(id=donacion_id)

	donacion.estado = 'Rechazada'
	donacion.fecha_aceptacion = date.today()
	donacion.save()

	producto = donacion.objecto_servicio
	producto.estado = 'Vigente'
	producto.save()
	return redirect('donacion:listar')

@login_required
def Cancelar(request, donacion_id):
	donacion = Donacion.objects.get(id=donacion_id)
	producto = donacion.objecto_servicio
	producto.estado = 'Vigente'
	producto.save()
	donacion.delete()
	return redirect('donacion:listar')

@login_required
def Perfil(request, donacion_id):
    donacion = Donacion.objects.get(id=donacion_id)
    donador = donacion.donador
    receptor = donacion.receptor
    objecto_servicio = donacion.objecto_servicio
    estado = donacion.estado
    fecha_donacion = donacion.fecha_donacion
    fecha_aceptacion = donacion.fecha_aceptacion

    contexto = {
    'donacion':donacion,
    }
    return render(request, "perfil_donacion.html", {'donacion':donacion})

apps/donacion/templates/listar_donaciones.html
{% extends "index.html" %}

{% block title %}
    Donaciones 
{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            {% for donacion in donaciones %}
                {% if not donacion and user.request == donacion.donador %}
                    <div class="container">
                        <p>No haz realizado donaciones, te invitamos a hacerlo!!</p>
                    </div>
                {% endif %}  
                <a href="{% url 'donacion:perfil' donacion.id %}"> 
                    <div class="col-lg-6 mb-4">
                        <div class="card shadow mb-4">
                        <!-- Card Header - Dropdown -->
                            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">ID: {{ donacion.id|upper }}</h6>
                                <div class="dropdown no-arrow">
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                         <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                    </a>
                                </div>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                <p> <b>Donador:</b> {{ donacion.donador|capfirst }}</p>
                                <p> <b>Objecto o servicio donado:</b> {{ donacion.objecto_servicio|capfirst }}</p>
                                <p> <b>Beneficiado:</b> {{ donacion.receptor|capfirst }}</p>
                                <p> <b>Estado de la donación:</b> {{ donacion.estado|capfirst }}</p>
                                <p> <b>Fecha de donación:</b> {{ donacion.fecha_donacion }}</p>

                                {% if donacion.fecha_aceptacion %}
                                    <p> <b>Fecha de aceptación/recepción de la donación:</b> {{ donacion.fecha_aceptacion }}</p>
                                {% endif %}

                                {% if donacion.estado == "Iniciada" and donacion.donador == request.user %}
                                    <a type="submit" class="btn btn-primary" href="{% url 'donacion:modificar' donacion.id %}">Modificar</a>
                                    <a type="submit" class="btn btn-danger" href="{% url 'donacion:cancelar' donacion.id %}">Cancelar</a>
                                {% endif %}

                                {% if donacion.estado == "Iniciada" and donacion.receptor == request.user %}
                                    <a type="submit" class="btn btn-primary" href="{% url 'donacion:aceptar' donacion.id %}">Aceptar</a>
                                    <a type="submit" class="btn btn-danger" href="{% url 'donacion:rechazar' donacion.id %}">Rechazar</a>
                                {% endif %}							
                            </div>
                        </div>
                    </div>

                    {% if not donacion %}
                        <div>
                            <p>No has realizado ninguna donacion, te invitamos a hacerlo!!</p>
                        </div>
                    {% endif %} 
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock contenido %}

apps/donacion/templates/modificar_donacion.html
{% extends "index.html" %}

{% block title %}
Modificar donación 
{% endblock %}

{% block barra_busqueda %} 
{% endblock barra_busqueda %}

{% block contenido %}

            <div class="col-lg-6 mb-4">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Modificar donación</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                <form action="" method="post">{% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                  <button class="btn btn-success" type="submit">Modificar</button>
                </form>
                </div>
              </div>
            </div>

{% endblock contenido %}

apps/donacion/templates/perfil_donacion.html
{% extends "index.html" %}

{% load static %}

{% block title %} 
   Productos 
{% endblock %}

{% block barra_busqueda %}

{% endblock barra_busqueda %}

{% block contenido %}

<div class="col-lg-6 mb-4">
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">{{ donacion.id|capfirst}}</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">

							<img src="{% static 'img/th2.png' %}" style="width: 150px;">
						 <hr class="sidebar-divider">
						<p> <b>donador:</b> {{ donacion.donador }} </p>
						<p> <b>objecto_servicio:</b> {{ donacion.objecto_servicio }} </p>
						<p> <b>receptor:</b> {{ donacion.receptor }} </p>
            <p> <b>Estado:</b> {{ donacion.estado }} </p>
            <p> <b>fecha_donacion:</b> {{ donacion.fecha_donacion }} </p>
            <p> <b>fecha_aceptacion:</b> {{ donacion.fecha_aceptacion }} </p>
					</div>
				</div>
   </div>
{% endblock contenido %}

apps/donacion/templates/registrar_donacion.html
{% extends "index.html" %}

{% block title %}
Registrar Donación 
{% endblock %}

{% block barra_busqueda %}

{% endblock barra_busqueda %}

{% block contenido %}


            <div class="col-lg-6 mb-4">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Registro de donación</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
    		    <form action="" method="post">{% csrf_token %}
    		        <table>
    		            {{ form.as_table }}
    		        </table>
                  <button class="btn btn-success" type="submit">Donar</button>
            	</form>
                </div>
              </div>
            </div>

{% endblock contenido %}