apps/usuario/urls.py
from django.urls import path

from . import views

app_name = 'usuario'
urlpatterns = [
	
	path('registrar', views.Registrar, name="registrar"),
	path('registrarme', views.RegistrarMe, name="registrarme"),
    path('modificar/<int:usuario_id>', views.Modificar, name='modificar'),
	path('listar', views.Listar, name="listar"),
	path('login', views.Login, name="login"),
	path('logout', views.Logout, name="logout"),
    path('inicio', views.Inicio, name='inicio'),
    path('perfil/<int:usuario_id>', views.Perfil, name='perfil'),
    path('cambiar_contrasena/<int:usuario_id>', views.Cambiar_contrasena, name='cambiar_contrasena'),

]

truek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('donacion/', include('apps.donacion.urls', namespace="donacion")),
    path('intercambio/', include('apps.intercambio.urls', namespace="intercambio")),
    path('usuario/', include('apps.usuario.urls', namespace="usuario")),
    path('producto/', include('apps.producto.urls', namespace="producto")),
    path('page/', include('apps.page.urls', namespace="page")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/page/templates/inicio2.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}TrueK{% endblock title %}</title>

  <!-- Custom fonts for this template-->
  <link rel="stylesheet" href="{% static 'js/fontawesome-free/css/all.min.css' %}  type="text/css">
  <link href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" >

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock css %}
    {{ form.media }}
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
      {% block barra_usuario %}
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-primary bg-primary topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
            
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <!--span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user|capfirst }}</span>
                <img class="img-profile rounded-circle" src="{{ usuario.photo.url }}">-->
              </a>
              <!-- Dropdown - User Information >
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Mi Perfil
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Cambiar contraseña
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'usuario:logout'%}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div-->
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->
        {% endblock barra_usuario %}
{% block contenido %}

<!-- Begin Page Content -->
<div class="container-fluid">
  <div class="row"> 
    <!-- Intercambios realizados -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Intercambios realizados
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">{{ numero_intercambios_aceptados }}
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

  <!-- Donaciones realizadas -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Donaciones realizadas
              </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ numero_donaciones_iniciadas }}
                </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

  <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Usuarios registrados
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">{{ usuarios }}
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

  <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Número de productos
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">{{ numero_productos }}
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-comments fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page Heading -->
<div class="container-fluid">
  <div class="row"> 
    <div class="col-xl-4 col-lg-4">
      <div class="card shadow mb-4">
        <!-- Card Body -->
        <div class="card-body">
          <h2> Con TRUEK puedes:</h2>
          <ul>
          <li>Ofrece y publica un objeto o servicio que quiere intercambiar</li>
          <li>Busca objetos/servicios que quieran obtener y hacer una proposición para algún objeto/servicio propio y espera una respuesta</li>
          <li>Solicite donaciones de objetos/servicios.</li>
          <li>Hacer donaciones de objetos/servicios.</li>
          </ul>
        <div align="center">
          <a href="{% url 'usuario:registrarme' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i>Registrate</a>
          <a href="{% url 'usuario:login' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i>Inicia Sesión</a>
        </div>
      </div>
    </div>
  </div>

      {% for producto in productos %}
        {% if not producto.dueno == request.user and producto.estado == "Vigente" %}
          <div class="col-lg-4 mb-4">
            <div class="card border-bottom-info shadow mb-4  py-1">
              <!-- Card Header - Dropdown -->
              <!-- Card Body -->
              <div class="card-body">
                <img src="{{producto.foto.url}}" style="width: 200px; border-radius: 8px; height: 200px;">
                  <hr class="sidebar-divider">
                  <p> <b>Descripción:</b> {{ producto.descripcion|capfirst }} </p>
                  <p> <b>Etiquetas:</b> {{ producto.etiquetas|capfirst }} </p>
                  <p> <b>Estado:</b> {{ producto.estado|capfirst }} </p>
              </div>
            </div>	
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>

<!-- End of Main Content -->
{% endblock contenido %}
{% block footer %}
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
{% endblock footer %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'js/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'js/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'js/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/Chart.js' %}"></script> 
    {% block js %}
    {% endblock js %}
</body>

</html>

apps/page/templates/pie_chart.html
{% block content %}
  <div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'
          ],
          label: 'Population'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

{% endblock %}

apps/page/templates/preguntas_frecuentes.html
{% extends "index.html" %}

{% block title %}
Preguntas frecuentes 
{% endblock %}

{% block contenido %}
<body>
<div class="container-fluid">
         <div class="panel-group" id="accordion">
          <div class="col-lg-12 col-md-6 mb-4">
          <div class="card border-left-warning shadow h-100 py-1" >
            <div class="panel panel-default">
                  <div class="panel-heading">
                     <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">&nbsp; 1. ¿Es Truek de uso libre?</a>
                     </h4>
                 </div>
                 <div id="collapse2" class="panel-collapse collapse">
                    <div class="panel-body">&nbsp; Sí, Truek es una aplicación web de uso gratuito.</div>
               </div>
            </div>
          </div>
        </div>
            <br>
          <div class="col-lg-12 col-md-6 mb-4">
          <div class="card border-left-warning shadow h-3 py-1" >
               <div class="panel panel-default">
                  <div class="panel-heading">
                     <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">&nbsp; 2. Los datos registrados en Truek son de uso libre?</a>
                     </h4>
                 </div>
                 <div id="collapse3" class="panel-collapse collapse">
                    <div class="panel-body">&nbsp; Sí, los datos de Truek son de libre uso.</div>
               </div>
            </div>
          </div>
        </div>

<br>
          <div class="col-lg-12 col-md-6 mb-4">
          <div class="card border-left-warning shadow h-3 py-1" >
            <div class="panel panel-default">
                  <div class="panel-heading">
                     <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">&nbsp; 3. Si sufro de una estafa, Truek responde por ello?</a>
                     </h4>
                 </div>
                 <div id="collapse4" class="panel-collapse collapse">
                    <div class="panel-body">&nbsp; No, Truek solo es un camino para agilizar los procesos de donación o intercambio entre personas pero la responsabilidad recae únicamente sobre los participantes y la información que ellos compartan.</div>
               </div>
            </div>
          </div>
        </div>
<br>
          <div class="col-lg-12 col-md-6 mb-4">
          <div class="card border-left-warning shadow h-3 py-1" >
                  <div class="panel panel-default">
                  <div class="panel-heading">
                     <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse5">&nbsp; 4. Se realiza alguna validación de los datos registrados por los usuarios de Truek?</a>
                     </h4>
                 </div>
                 <div id="collapse5" class="panel-collapse collapse">
                    <div class="panel-body">&nbsp; No, Truek no realiza ningún tipo de validación y no puede garantizar la veracidad de la información registrada por sus usuarios.</div>
               </div>
            </div>
       </div>
     </div>
   </div>
    </div>

</body>
{% endblock contenido %}