apps/intercambio/urls.py
from django.urls import path

from . import views

app_name = 'intercambio'
urlpatterns = [

	path('registrar_desde_producto/<int:producto_id>', views.RegistrarDesdeProducto, name="registrar_desde_producto"),
	path('registrar', views.Registrar, name="registrar"),
    path('modificar/<int:intercambio_id>', views.Modificar, name='modificar'),
	path('listar', views.Listar, name="listar"),
	path('aceptar/<int:intercambio_id>', views.Aceptar, name='aceptar'),
	path('rechazar/<int:intercambio_id>', views.Rechazar, name='rechazar'),
	path('cancelar/<int:intercambio_id>', views.Cancelar, name='cancelar'),
    path('perfil/<int:intercambio_id>', views.Perfil, name='perfil'),
]

truek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('donacion/', include('apps.donacion.urls', namespace="donacion")),
    path('intercambio/', include('apps.intercambio.urls', namespace="intercambio")),
    path('usuario/', include('apps.usuario.urls', namespace="usuario")),
    path('producto/', include('apps.producto.urls', namespace="producto")),
    path('page/', include('apps.page.urls', namespace="page")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/intercambio/models.py
from django.db import models
from django.utils import timezone

from datetime import date, datetime

from apps.usuario.models import Usuario
from apps.producto.models import Producto

class Intercambio(models.Model):

	ESTADOS = (
		('Iniciado','Iniciado'),
		('Aceptado','Aceptado'),
		('Rechazado','Rechazado'),
	)

	oferente = models.ForeignKey(Usuario, related_name="oferente", on_delete = models.CASCADE)
	producto_del_oferente = models.ForeignKey(Producto, related_name="productos_del_oferente", on_delete = models.CASCADE)
	producto_del_receptor = models.ForeignKey(Producto, related_name="productos_del_receptor", on_delete = models.CASCADE)
	receptor = models.ForeignKey(Usuario, related_name="receptor", on_delete = models.CASCADE)
	estado = models.CharField(max_length=254, choices = ESTADOS)
	fecha_solicitud_intercambio = models.DateTimeField(verbose_name= "Fecha de solicitud de intercambio", blank=False, default=timezone.now)
	fecha_aceptacion_intercambio = models.DateField(verbose_name= "Fecha de aceptación de intercambio", blank=True, null=True)

apps/intercambio/forms.py
from django import forms

from .models import Intercambio, Producto, Usuario

class RegistrarIntercambioForm(forms.ModelForm):
	def __init__(self, oferente, *args, **kwargs):
		super(RegistrarIntercambioForm, self).__init__(*args, **kwargs)
		self.fields['producto_del_oferente'].queryset = Producto.objects.filter(dueno=oferente).exclude(estado='Donado').exclude(estado='Intercambiado').exclude(estado='En proceso')
		self.fields['producto_del_receptor'].queryset = Producto.objects.exclude(dueno=oferente).exclude(estado='Donado').exclude(estado='Intercambiado').exclude(estado='En proceso')

	def clean(self):
		cleaned_data = super().clean()
		producto_del_oferente = cleaned_data.get("producto_del_oferente")
		producto_del_receptor = cleaned_data.get("producto_del_receptor")


		if producto_del_oferente == producto_del_receptor:
			mensaje2 = "El producto de intercambio no puede ser el mismo"
			self.add_error('producto_del_receptor', mensaje2)


	class Meta:
		model = Intercambio
		fields = ('producto_del_oferente', 'producto_del_receptor',)

class RegistrarIntercambioDesdeProductoForm(forms.ModelForm):
	def __init__(self, oferente, producto_del_receptor, *args, **kwargs):
		super(RegistrarIntercambioDesdeProductoForm, self).__init__(*args, **kwargs)
		self.fields['producto_del_oferente'].queryset = Producto.objects.filter(dueno=oferente).exclude(estado='Donado').exclude(estado='Intercambiado').exclude(estado='En proceso')
		self.fields['producto_del_receptor'].queryset = Producto.objects.filter(id=producto_del_receptor.id)
		self.initial["producto_del_receptor"] = producto_del_receptor


	def clean(self):
		cleaned_data = super().clean()
		producto_del_oferente = cleaned_data.get("producto_del_oferente")
		producto_del_receptor = cleaned_data.get("producto_del_receptor")


		if producto_del_oferente == producto_del_receptor:
			mensaje2 = "El producto de intercambio no puede ser el mismo"
			self.add_error('producto_del_receptor', mensaje2)


	class Meta:
		model = Intercambio
		fields = ('producto_del_oferente', 'producto_del_receptor',)

class ModificarIntercambioForm(forms.ModelForm):

	class Meta:
		model = Intercambio
		fields = ('producto_del_oferente', 'producto_del_receptor',)

apps/intercambio/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from datetime import date, datetime

from .forms import RegistrarIntercambioForm, ModificarIntercambioForm, RegistrarIntercambioDesdeProductoForm
from .models import Intercambio, Producto

@login_required
def Registrar(request):
	
	if request.method == 'POST':
		form = RegistrarIntercambioForm(request.user, request.POST)
		if form.is_valid():
			usuario_actual = Intercambio(oferente = request.user)
			intercambio = form.save(commit=False)
			intercambio.oferente = request.user
			intercambio.receptor = intercambio.producto_del_oferente.dueno
			intercambio.receptor = intercambio.producto_del_receptor.dueno
			intercambio.estado = 'Iniciado'
			intercambio.save()

			producto_del_oferente = intercambio.producto_del_oferente
			producto_del_oferente.estado = 'En proceso'
			producto_del_oferente.save()
			return redirect('intercambio:listar')
	else:
		form = RegistrarIntercambioForm(request.user)
	return render(request, 'registrar_intercambio.html', {'form': form})

@login_required
def RegistrarDesdeProducto(request, producto_id):
	producto_del_receptor = Producto.objects.get(id=producto_id)	
	if request.method == 'POST':
		form = RegistrarIntercambioDesdeProductoForm(request.user, producto_del_receptor, data=request.POST)
		if form.is_valid():
			usuario_actual = Intercambio(oferente = request.user)
			intercambio = form.save(commit=False)
			intercambio.oferente = request.user
			intercambio.receptor = intercambio.producto_del_oferente.dueno
			intercambio.receptor = intercambio.producto_del_receptor.dueno
			intercambio.estado = 'Iniciado'
			intercambio.save()

			producto_del_oferente = intercambio.producto_del_oferente
			producto_del_oferente.estado = 'En proceso'
			producto_del_oferente.save()
			return redirect('intercambio:listar')
	else:
		form = RegistrarIntercambioDesdeProductoForm(request.user, producto_del_receptor)
	return render(request, 'registrar_intercambio.html', {'form': form})

@login_required
def Modificar(request, intercambio_id):
	intercambio = Intercambio.objects.get(id=intercambio_id)
	form = ModificarIntercambioForm(instance=intercambio)
	if request.method == "POST":
		form = ModificarIntercambioForm(request.POST, instance=intercambio)
		if form.is_valid():
			intercambio = form.save(commit=False)
			intercambio.save()
			return redirect('intercambio:listar')
	return render(request, 'modificar_intercambio.html',{'form': form})

@login_required
def Listar(request):
	from django.db.models import FilteredRelation, Q
	intercambios = Intercambio.objects.filter(Q(oferente=request.user)|Q(receptor=request.user))
	return render(request, "listar_intercambios.html", {'intercambios':intercambios})

@login_required
def Aceptar(request, intercambio_id):
	intercambio = Intercambio.objects.get(id=intercambio_id)
	intercambio.estado = 'Aceptado'
	intercambio.fecha_aceptacion_intercambio = date.today()
	intercambio.save()

	producto_del_oferente = intercambio.producto_del_oferente
	producto_del_oferente.estado = 'Intercambiado'
	producto_del_oferente.dueno = request.user
	producto_del_oferente.save()

	producto_del_receptor = intercambio.producto_del_receptor
	producto_del_receptor.estado = 'Intercambiado'
	producto_del_receptor.dueno = intercambio.oferente
	producto_del_receptor.save()

	contexto = { 'intercambio':intercambio, 'producto_del_oferente':producto_del_oferente, 'producto_del_receptor':producto_del_receptor }
	return redirect('intercambio:listar')

@login_required
def Rechazar(request, intercambio_id):
	intercambio = Intercambio.objects.get(id=intercambio_id)
	intercambio.estado = 'Rechazado'
	intercambio.fecha_aceptacion_intercambio = date.today()
	intercambio.save()
	producto_del_oferente = intercambio.producto_del_oferente
	producto_del_oferente.estado = 'Vigente'
	producto_del_oferente.save()
	return redirect('intercambio:listar')

@login_required
def Cancelar(request, intercambio_id):
	intercambio = Intercambio.objects.get(id=intercambio_id)
	producto_del_oferente = intercambio.producto_del_oferente
	producto_del_oferente.estado = 'Vigente'
	producto_del_oferente.save()
	intercambio.delete()
	return redirect('intercambio:listar')

@login_required
def Perfil(request, intercambio_id):
    intercambio = Intercambio.objects.get(id=intercambio_id)
    producto_del_oferente = intercambio.producto_del_oferente
    producto_del_receptor = intercambio.producto_del_receptor
    receptor = intercambio.receptor
    estado = intercambio.estado
    fecha_solicitud_intercambio = intercambio.fecha_solicitud_intercambio
    fecha_aceptacion_intercambio = intercambio.fecha_aceptacion_intercambio

    contexto = {
    'intercambio':intercambio,
    }

    return render(request, "perfil_intercambio.html", {'intercambio':intercambio})

apps/intercambio/templates/listar_intercambios.html
{% extends "index.html" %}

{% block title %}
Intercambios 
{% endblock %}

{% block contenido %}

<div class="container">
    <div class="row">
              
        {% for intercambio in intercambios %}
        {% if not intercambio and user.request == intercambio.oferente %}
            <div class="container">
                <p>No haz realizado ningún intercambio, te invitamos a hacerlo!!</p>
            </div>
            {% endif %}
            {% if intercambio.oferente == request.user or intercambio.receptor == request.user %}
            <a href="{% url 'intercambio:perfil' intercambio.id %}"> 
            <div class="col-lg-6 mb-4">
            <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">ID: {{ intercambio.id|upper }}</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
            <p> <b>Oferente:</b> {{ intercambio.oferente|capfirst }}</p>
            <p> <b>Producto 1:</b> {{ intercambio.producto_del_oferente|capfirst }}</p>	
            <p> <b>Producto 2:</b> {{ intercambio.producto_del_receptor|capfirst }}</p>
            <p> <b>Receptor:</b> {{ intercambio.receptor|capfirst }}</p>
            <p> <b>Estado del intercambio:</b> {{ intercambio.estado|capfirst }}</p>
            <p> <b>Inicio del intercambio:</b> {{ intercambio.fecha_solicitud_intercambio }}</p>
            {% if intercambio.fecha_aceptacion_intercambio %}
            <p> <b>Fecha de aceptación/recepción del intercambio:</b> {{ intercambio.fecha_aceptacion_intercambio }}</p>
            {% endif %}	
            {% if intercambio.estado == "Iniciado" and intercambio.receptor == request.user %}
            <a type="submit" class="btn btn-primary" href="{% url 'intercambio:aceptar' intercambio.id %}">Aceptar</a>
            <a type="submit" class="btn btn-danger" href="{% url 'intercambio:rechazar' intercambio.id %}">Rechazar</a>
            {% endif %}	
            {% if intercambio.oferente == request.user and intercambio.estado == "Iniciado" %}
            <a type="submit" class="btn btn-primary" href="{% url 'intercambio:modificar' intercambio.id %}">Modificar</a>
            <a type="submit" class="btn btn-danger" href="{% url 'intercambio:cancelar' intercambio.id %}">Cancelar</a>
            {% endif %}							            			            
            </div>
            </div>
            </div>
            </a>
            {% endif %}

 
        {% endfor %}
    </div>
</div>
{% endblock contenido %}

apps/intercambio/templates/modificar_intercambio.html
{% extends "index.html" %}
{% block title %}
Modificar intercambio 
{% endblock %}

{% block barra_busqueda %} 
{% endblock barra_busqueda %}

{% block contenido %}
            <div class="col-lg-6 mb-4">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Modificar intercambio</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
            <form action="" method="post">{% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                  <button type="submit" class="btn btn-success">Enviar</button>
            </form>
                </div>
              </div>
            </div>
{% endblock %}

apps/intercambio/templates/perfil_intercambio.html
{% extends "index.html" %}

{% load static %}

{% block title %} 
   Productos 
{% endblock %}

{% block barra_busqueda %}

{% endblock barra_busqueda %}

{% block contenido %}

<div class="col-lg-6 mb-4">
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">{{ intercambio.id|capfirst}}</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">

							<img src="{% static 'img/th2.png' %}" style="width: 150px;">
						 <hr class="sidebar-divider">
						<p> <b>Oferente:</b> {{ intercambio.oferente }} </p>
						<p> <b>Producto_del_oferente:</b> {{ intercambio.producto_del_oferente }} </p>
						<p> <b>Producto_del_receptor:</b> {{ intercambio.producto_del_receptor }} </p>
            <p> <b>Receptor:</b> {{ intercambio.receptor }} </p>
            <p> <b>Estado:</b> {{ intercambio.estado }} </p>
            <p> <b>Fecha_solicitud_intercambio:</b> {{ intercambio.fecha_solicitud_intercambio }} </p>
            <p> <b>Fecha_aceptacion_intercambio:</b> {{ intercambio.fecha_aceptacion_intercambio }} </p>
					</div>
				</div>
   </div>
{% endblock contenido %}

apps/intercambio/templates/registrar_intercambio.html
{% extends "index.html" %}

{% block title %}
Registrar Intercambio 
{% endblock %}

{% block barra_busqueda %} 
{% endblock barra_busqueda %}

{% block contenido %}

            <div class="col-lg-6 mb-4">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Registro de intercambio</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
		    <form action="" method="post">{% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                  <button type="submit" class="btn btn-success">Enviar</button>
            </form>
                </div>
              </div>
            </div>

{% endblock contenido %}